### ISSUE TITLE
是否可以和tree结合呢

### ISSUE THREAD

**Issue by buzai** [bighuang624/yuki#1]

**Comment by bighuang624** [comment]
呃，我才看到...为什么 Github 没有 issues 提醒？

具体是怎么一个结合法？@buzai

**Comment by buzai** [comment]
哈这个好久了我都快忘了，tree这个命令可以输出一个文件层级目录，将tree生成的目录写到readme里要怎么弄呢

**Comment by bighuang624** [comment]
emmm，因为这个工具是我平时用来做目录的，所以不打算将 tree 生成的目录写到 README 里。你可以直接 tree 完了复制粘贴，要比这个工具能够完成的工作给人做所要花费的工作量小太多了。
但是你给我了一个想法，可能之后我会加一个参数，比如 -t，然后将写到 README 中的内容按照 tree 的格式显示到命令行界面中。:)@buzai

**Comment by buzai** [comment]
@bighuang624  谢谢哈，我就是当时有一个想法
